### PR TITLE
Create strasbourg and Graffalgar.

### PR DESCRIPTION
**Pull request by francois2metz**

### CODE REVIEW

**Comment by avernois** [comment]
Hello @francois2metz 

A new town, this is awesome! thanks.
But as Strasbourg is a brand new location, it needs its own entry into locations/locations.json.
Could you add it?

[The (short) doc can be found here: ](https://github.com/avernois/devfriendlyplaces#add-a-new-location)
If you have any difficulties, I'll be happy to provide help.

thks.

**Comment by francois2metz** [comment]
Sure, i'll do it.

**Comment by francois2metz** [comment]
Done. It's quite difficult to test on my local environments. Any tips to share?

**Comment by francois2metz** [comment]
Okay, found a way to test it. Looks good.

**Comment by avernois** [comment]
Awesome! 

thanks!

(to test, on linux, you can add en entry in your /etc/host that assign rennes.devfriendlyplaces.local (or the city you want) to 127.0.0.1)

**Pull request merged**
