### PR TITLE
Fix: replace location.name by location.title to fix %20 problems in the ...

### PR DESCRIPTION
**Pull request by pointbar**
...location's urls

### CODE REVIEW

**Comment by avernois** [comment]
Thats awesome!

But could you make different pull requests ? (at least one for the new places, and one for the technical stuff ?)

thanks.

**Comment by pointbar** [comment]
Yep, sorry for the convenient.

I tried to do that, but I failed.
Do I have to put my changes in a separate branch?

See ya!

**Comment by avernois** [comment]
Yep. Pull request are based on branches.
To have distinct pull request you need distinct branches.

**Comment by avernois** [comment]
I split the pull request. So this one is replaced by #140 and #141

**Pull request closed without merging**
