### PR TITLE
change address of Coolworking

### PR DESCRIPTION
**Pull request by nostradamnit**
simple address change

### CODE REVIEW

**Comment by avernois** [comment]
Thanks

**Comment by nostradamnit** [comment]
Hey Antoine,

I've got another one but I didn't know how to do a pull request by
commit... I've added Marmande to the map. I'll create another pull request.

Thanks,
Sam

**Comment by nostradamnit** [comment]
nevermind, you got it already :)

Thx,
Sam

**Comment by avernois** [comment]
Afaik, you can make a pull request "per commit".
Pull request are per branch. So if you want to make different pull request you have to make your changes in different branches.

But, in that case, all commits in the same PR is fine for me.

I only require different PR if you want to add/update places __and__ add/change features

Hope this helps

Thanks

**Pull request merged**
