### PR TITLE
Remove coworking

### PR DESCRIPTION
**Pull request by avernois**
I first imagined [devfriendlyplaces.net](http://devfriendlyplaces.net) as a list of places where I could go, seat myself at a table and start doing things and know if I will be able to plug my laptop, or order a tea, coffe, something to eat.
I wanted it to be a list of all those places not meant for work but where I could work while being surrounding by people living their life (or not).

Coworking spaces are not that kind of spaces. They are places meant for work. All people here are there to work. They surely are great places. But they are not for me.
I don't feel fine being asked what I'm doing, how long I will stay, why I'm leaving while I'm only here for 20min. They meant well, it has always been nice and friendly, and they sure are great places for some people. Just not for me, they are not what I'm looking for.

* Why now?
I recently went to Paris with few spare hours to spend. I wanted to find a place to work on a pet project, and paris.devfriendlyplaces.net showed lot of points. That sounds great. All (but 2) were coworking spaces, places where I did not want to go, and so I suddenly feel lost and that some cleaning was required so devfriendlyplaces becomes what it meant to me, again. Here it is.

* But there are some coworking left in the list?
Yep, I think three of them in Berlin, Dakar and Paris. It seems that these places are also regular coffee shop where non working people could go. So I left them. If you know it's not the case, let me know (or make a PR on the "remove_coworking" branch that remove them.
The same if I remove places I should not have.

I'm sad that this move will make some locations to disappear.

### CODE REVIEW

**Comment by chadrien** [comment]
If some users still want to be proposed coworking spaces, a 2nd step could be to add an option like "Show coworking spaces : on/off"

**Comment by FabienTregan** [comment]
When I use DFPs, I'm definitively looking for the some place where I can freely work for a short time.
If you hade a filtering capability, then I'd like to have the default setting to be hiding coworking places.

**Comment by rehia** [comment]
I agree with this.
Even if it seems that something like DFP focused on coworking places could be helpful.
But I don't use DFP for them. I use it for places where I can grab a drink, where I don't feel in a work place.
Note: I'm not against a filter. It's up to you!

**Comment by avernois** [comment]
Filtering options are not in dev plan (to be honest, the only thing currently in dev plan is to take time to test and merge #145. I should have done that almost a year ago :).
I know some people would enjoy filtering options. If you want it to happen, open an issue so we can talk about it (i suspect it will require a quite big refactoring).

**Comment by mjambert** [comment]
Maybe you should be more explicit on the site ...?

Shouldn't it also be made explicit to people owning places referenced :) ? As the site becomes more and more popular, it sounds natural to ask people if they mind being referenced on this site ?

**Comment by avernois** [comment]
@mjambert explicit about what? I'm not sure to understant what you mean.

and I never really thought about to get consent of places owners as it's about public places. But that's an interesting idea, probably will have to think about it at some point. (but, even if I have no figure to back it up, I'm quite sure DFP is not as popular as you think :)

**Comment by SamirTalwar** [comment]
Agreed. None of the places I've put up on the London map are co-working spaces, and I wouldn't feel comfortable with them. I would be very happy with a toggle, regardless of the default.

**Comment by mjambert** [comment]
more explicit about what is *your* definition of a dev friendly place (and what you expect to collect on the site).

As it is : 
"DEV FRIENDLY PLACES"
Pick a city and find a place for coding

And on github :

"A collection of nice places where developers can work fine and some useful informations about these places (wifi ? power ? ...) on the map of a location."

Strictly speaking, co-working offices match both descriptions. I agree that it is not what I call and you call a nice place to work, but it is unclear.

**Comment by mjambert** [comment]
And note that there is a difference between a public place and a private place where public is welcome...

**Comment by avernois** [comment]
@mjambert : I already added a section about "What kind of places can I add?" see 52a8cade92222468eb29f28d730f9ab553da53ab

**Comment by elefevre** [comment]
I admit I'm a bit confused by the issue here.

@avernois, you say that you do not like being talked to in coworking spaces. Well, I agree, but I have been to about 4-5 in the past few months, and nowhere was anyone talking to me.
My only issue is with *some* coworking spaces where people are expected to come on a daily basis. That does not work for me, but actually many coworking spaces bill by the hour.

On the other hand, I've been to a few cafés that offer free wifi and a few seats where you could plug your laptop. Unfortunately, those seats were generally taken (does that count as offering power, then?), and the wifi was poor (does that count as offering wifi?), so that did not work well for me. Seats are not always best for coding, too.

In the end, the spectrum is wide. Some coworking spaces charge by the day (or even by the month), some by the hour. Some demand that you buy a drink regularly (and still bill themselves as coworking spaces). Some have music that is too loud for me. Many do not have the problems you faced.

Until the number of spots is overwhelming, I'd recommend erring on the inclusive side. Maybe add a "notes" section where specifics can be given ("half of seats have power and they are all taken by 11am; charge on a daily basis").

**Comment by avernois** [comment]
Thanks all for your feedback. I'll merge this PR and remove coworking space for now.

**Pull request merged**
