### PR TITLE
Add a page to list all available locations

### PR DESCRIPTION
**Pull request by avernois**
this is a work in progress for #63

### CODE REVIEW

**Comment by avernois** [comment]
Ok, so I have a locations.html that build the list from the locations/locations.json file.
Any help to add CSS is welcome (ping @pointbar @ludopradel :)

**Comment by pointbar** [comment]
ul {
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 14px;
    line-height: 1.42857143;
    max-width: 300px;
    padding-left: 0;
    margin: 10%;
}

li {
    display: block;
    border-top-left-radius: 4px;
    border-top-right-radius: 4px;
    position: relative;
    padding: 10px 15px;
    margin-bottom: -1px;
    background-color: #fff;
    border: 1px solid #ddd;
}

li:hover {
    background: #eee;
}

li a {
    display: block;
    text-decoration: none;
    color: #555;
}

**Comment by pointbar** [comment]
Perhaps buildLocations() must just return <a>, it'll be easy to insert an header

**Comment by avernois** [comment]
Thanks for the CSS.

I don't understand the comment about "return" (remember, i'm a newbie in js :)

**Comment by avernois** [comment]
done in #132

**Pull request closed without merging**
