### PR TITLE
Update toulouse.json

### PR DESCRIPTION
**Pull request by cba85**

### CODE REVIEW

**Comment by avernois** [comment]
Hello,

thanks for your contribution. 
I waited to merge it because the place seems to be a co-working space that wouldn't say its name. As I'm in Toulouse, I thought I would go see by myself. And I didn't :( (and probably won't in a reasonnable amount of time).

So, I ask you: is it really a nice spot where you would go for non work related reasons?

thanks.

**Comment by cba85** [comment]
Hello,

After spending some times in this place, it's not really a coworking because I didn't find the "cowork spirit".
I think it's a coffee shop to stay for a long time.

It's a place for work because there is wifi and print service included.
But there are stuff non work related like games, paperboard, sofa...
I saw people talking in group, play games...

There are people who work and people who spend good times.
That's why depending of the people inside, this place can be noisy and not really good for reflexion.

It's really difficult to categorize this place.

**Comment by AntoineCezar** [comment]
Tried the place myself a few times now and it doesn't feels like a coworking. I think a lot a people work here because it's really quiet. But, it's more a coffeeshop where you pay the time spent rather than the meal.

**Comment by AntoineCezar** [comment]
Asked them what is the concept. They said: It's something between the coworking and the tea room. It's a working space without restriction on who can come and no required subcription.

**Comment by avernois** [comment]
Thanks for your feedback @cba85 and @AntoineCezar. 
Sounds like they fit well for devfriendlyplaces \o/

**Pull request merged**
