### PR TITLE
First place in Cahors

### PR DESCRIPTION
**Pull request by d-plaindoux**
Initial Cahors dev friendly place.

### CODE REVIEW

**Comment by avernois** [comment]
Seems that you forgot a quote on the address line :)

**Comment by d-plaindoux** [comment]
forgotten quote added

**Comment by avernois** [comment]
Merged. Thanks \o/

**Comment by avernois** [comment]
Damn. I did not realize Cahors is a new places.
You also need to add it in the locations/locations.json

**Pull request merged**
