### PR TITLE
Add Rennes location and some places

### PR DESCRIPTION
**Pull request by XavCC**
More to come soon

### CODE REVIEW

**Comment by avernois** [comment]
Hello @XavCC. 

A new town, this is awesome! thanks.
But as Rennes is a brand new location, it needs its own entry into locations/locations.json.
Could you add it?

thks.

**Comment by XavCC** [comment]
I just delete the old fork and replace it by [this one](https://github.com/XavCC/devfriendlyplaces/tree/master/locations) adding Rennes city and places

**Comment by avernois** [comment]
Hello,

thanks for the update. But Rennes is still missing in locations.json.

[The (short) doc can be found here: ](https://github.com/avernois/devfriendlyplaces#add-a-new-location)
If you have any difficulties, I'll be happy to provide help.

thanks.

**Comment by XavCC** [comment]
@avernois I felt stupid, then i find my mistake and now i learn something and add rennes in locations.json + new place in rennes.json.

i think it's ok and complete now

Thank's a lot

**Comment by avernois** [comment]
Hello,
I think you forgot to push your last commit :) 
(this PR contains only the create/update of rennes.json, you can see changed file here: https://github.com/avernois/devfriendlyplaces/pull/187/files)

**Pull request closed without merging**
