### PR TITLE
Use of geojson

### PR DESCRIPTION
**Pull request by francois2metz**
Ahem. So @egaillot and I, we refactored as an exercise all places files to use the fantastic geojson standard instead of the custom json format you had. You may want to use it.

It brings some benefits:
- it's a standard 
- and you can use github to preview the geojson files

Awesome isn't it?

We did some improvements to the test suite in order to run them easily (without phantom).

### CODE REVIEW

**Comment by francois2metz** [comment]
I created 2 separate branches to split this one if you want: 

- refactoring tests: https://github.com/avernois/devfriendlyplaces/compare/master...francois2metz:refactor_tests
- Remove some locations: https://github.com/avernois/devfriendlyplaces/compare/master...francois2metz:cleanup_locations

**Comment by francois2metz** [comment]
I opened 2 PRs #192 and #193 to cleanup this one. While it's not merged, the correct commit range is: https://github.com/avernois/devfriendlyplaces/pull/191/files/d8996daed5beac2ccc073427ecc3a1e5c1e65ee7..dcea3542afacdf2b0191843ee181b6474157f13f#diff-3c9aeac206d50f871576ea9d38da8dfa

**Comment by avernois** [comment]
Hello,

sorry for the late answer. This looks awesome, I was thinking of that move to GeoJSON for quite a while.
I'll check the code this morning and merge if everything looks fine.

**Comment by avernois** [comment]
Well, when I look at the resulting json, I remember why I did not do it earlier :)
I wonder if it's not too complex to be written "by hand". With the current (I think easy) flat format, most of PR I receive have errors. Most of them are detected with 'jq' (and we could probably enforce it by creating a schema to check files  against)

I like the idea of using a "standard" format, but I'm not sure that it worth the induce complexity.

I really don"t know what to do on that one. I'm open for comments/advice/opinion/suggestion :)

**Comment by francois2metz** [comment]
I agree with the format :)

One solution it to keep the current one, then pre-compile the site to transform the original json to geojson on deploy.

Another solution I found is to use http://geojson.io.

**Pull request closed without merging**
